breakout:
  env_id: "BreakoutNoFrameskip-v4"
  file_name: "Breakout04_Rainbow"
  atari: true
  max_steps: 27000
  eval_freq: 1000000 
  a2c:
    steps: 10000000
    num_envs: 16 
    n_steps: 5   
    lr: 0.0002
  ppo:
    steps: 10000000
    n_steps: 128
    num_envs: 8
    log_freq: 1000
    lr: 0.00025
    entropy-weight: 0.01
    value-weight: 1.0



